# Generated by Django 6.0.7 on 2026-08-27 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'start_datetime', 'end_datetime'], name='events_even_user_id_ec8426_idx'),
        ),
    ]
