# Generated by Django 6.0.7 on 2026-07-25 08:02

import budget.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('category_budgets', models.JSONField(default=budget.models.default_category_budgets)),
                ('warning_thresholds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=budget.models.default_warning_thresholds)),
                ('alerted_thresholds', models.JSONField(default=budget.models.default_alerted_thresholds)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
