# Generated by Django 6.0.7 on 2026-08-24 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('password_reset', 'Password Reset'), ('delete_account', 'Delete Account')], max_length=30)),
                ('otp_hash', models.CharField(max_length=255)),
                ('otp_expires_at', models.DateTimeField()),
                ('resend_available_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account OTP',
                'verbose_name_plural': 'account OTPs',
                'indexes': [models.Index(fields=['user', 'purpose'], name='users_accou_user_id_e55c00_idx')],
            },
        ),
    ]
